apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-build
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/demo-build/demo-build@sha256:9c97f9ad62719e26c3e4368527ceb2297a266289fa6c9c0e328ec90811e1e24d
        name: my-java-springboot
        resources: {}
status: {}
