apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-build
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-build
    app.kubernetes.io/part-of: demo-build
  name: demo-build
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: demo-build
status:
  loadBalancer: {}
